### ISSUE TITLE
[BUG] Code is non-compatible with Python 3.9

### ISSUE THREAD

**Issue by Matthieu-LAURENT39** [nexy7574/niobot#7]
**Describe the bug**
The minimal supported version right now is 3.9, but the library uses features from Python 3.10.
While the lack of the function is handled by the library to avoid a crash, it gives some inconsistent results based on Python version, which is undesirable.

**To Reproduce**
N/A

**Expected behavior**
The program uses only features from Python 3.9 and earlier, or has a minimal supported version of Python 3.10.

**Additional context**
The function in question is [platform.freedesktop_os_release()](https://docs.python.org/3/library/platform.html), added in Python 3.10, and used on [line 142 of `__main__.py`](https://github.com/nexy7574/niobot/blob/9dcec57bcff39e233417b43fb13132747f6081b0/src/niobot/__main__.py#L142C1-L142C27)

**Comment by nexy7574** [comment]
Adding wontfix as this issue is related to a version of python that will soon have support dropped, and is also a minor output difference that doesn't affect the command much.

The only solution I can think of to actually solve this bug is to manually parse /etc/os-release, however that's more trouble than its worth given the circumstances.
